package Hibernate;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * Imovel2 generated by hbm2java
 */
public class Imovel2  implements java.io.Serializable {


     private String matricula;
     private String nome;
     private String municipio;
     private String comarca;
     private String uf;
     private String area;
     private String tipoProcesso;
     private String nomeArquivo;
     private String demais;

    public Imovel2() {
    }

	
    public Imovel2(String matricula, String municipio, String comarca, String uf, String area, String tipoProcesso, String nomeArquivo) {
        this.matricula = matricula;
        this.municipio = municipio;
        this.comarca = comarca;
        this.uf = uf;
        this.area = area;
        this.tipoProcesso = tipoProcesso;
        this.nomeArquivo = nomeArquivo;
    }
    public Imovel2(String matricula, String nome, String municipio, String comarca, String uf, String area, String tipoProcesso, String nomeArquivo, String demais) {
       this.matricula = matricula;
       this.nome = nome;
       this.municipio = municipio;
       this.comarca = comarca;
       this.uf = uf;
       this.area = area;
       this.tipoProcesso = tipoProcesso;
       this.nomeArquivo = nomeArquivo;
       this.demais = demais;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getComarca() {
        return this.comarca;
    }
    
    public void setComarca(String comarca) {
        this.comarca = comarca;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getTipoProcesso() {
        return this.tipoProcesso;
    }
    
    public void setTipoProcesso(String tipoProcesso) {
        this.tipoProcesso = tipoProcesso;
    }
    public String getNomeArquivo() {
        return this.nomeArquivo;
    }
    
    public void setNomeArquivo(String nomeArquivo) {
        this.nomeArquivo = nomeArquivo;
    }
    public String getDemais() {
        return this.demais;
    }
    
    public void setDemais(String demais) {
        this.demais = demais;
    }




}


