package Hibernate;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * ProprietarioimoveliId generated by hbm2java
 */
public class ProprietarioimoveliId  implements java.io.Serializable {


     private int idProprietario;
     private String codIncra;

    public ProprietarioimoveliId() {
    }

    public ProprietarioimoveliId(int idProprietario, String codIncra) {
       this.idProprietario = idProprietario;
       this.codIncra = codIncra;
    }
   
    public int getIdProprietario() {
        return this.idProprietario;
    }
    
    public void setIdProprietario(int idProprietario) {
        this.idProprietario = idProprietario;
    }
    public String getCodIncra() {
        return this.codIncra;
    }
    
    public void setCodIncra(String codIncra) {
        this.codIncra = codIncra;
    }




}


