/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsuarioDAO;
import java.awt.Component;
import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Proprietario;

/**
 *
 * @author USuario
 */
public class JDialogPProprietario extends javax.swing.JDialog {

    static String id;
    static String nome;
    static String cpf;
    static String rg;

    /**
     * Creates new form JDialogPDisciplina
     */
    public JDialogPProprietario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        String Nome;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Proprietário");

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTablePesquisa.setBackground(new java.awt.Color(204, 204, 204));
        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_ Proprietario", "Nome", "CPF", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablePesquisa.setColumnSelectionAllowed(true);
        jTablePesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTablePesquisa.setRowHeight(20);
        jTablePesquisa.setRowMargin(2);
        jTablePesquisa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTablePesquisaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);
        jTablePesquisa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton3.setText("Visualizar Completo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        if ((jTextField1.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Serao Pesquisado Todos");
            DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
            tableModel.setNumRows(10);
        }

            List<Proprietario> receber = new ArrayList();

            try {
                UsuarioDAO b = new UsuarioDAO();
                receber = b.procuraUser("%" + jTextField1.getText() + "%");
                if (receber.size() == 0) {
                    DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
                    int n = tableModel.getRowCount();
                    for (int i = 0; i < n; i++) {
                        jTablePesquisa.setValueAt(null, i, 0);
                        jTablePesquisa.setValueAt(null, i, 1);
                        jTablePesquisa.setValueAt(null, i, 2);
                        jTablePesquisa.setValueAt(null, i, 3);
                    }
                    JOptionPane.showMessageDialog(null, "NAO ENCONTRADO");
                }
                for (int i = 0; i < receber.size(); ++i) {

                    DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
                    tableModel.setNumRows(receber.size());
                    jTablePesquisa.setValueAt(receber.get(i).getIdProprietario(), i, 0);
                    jTablePesquisa.setValueAt(receber.get(i).getNome(), i, 1);
                    jTablePesquisa.setValueAt(receber.get(i).getCpfcnpj(), i, 2);
                    jTablePesquisa.setValueAt(receber.get(i).getRg(), i, 3);
                }

            } catch (Exception ex) {
                Logger.getLogger(JDialogPProprietario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage() + "\n");
            }

        
    }//GEN-LAST:event_jTextField1ActionPerformed
    public static void Dados(String ID, String N, String C, String R) {
        id = ID;
        nome = N;
        cpf = C;
        rg = R;

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if ((jTextField1.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Serao Pesquisado Todos");
            DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
            tableModel.setNumRows(10);
        }

            List<Proprietario> receber = new ArrayList();

            try {
                UsuarioDAO b = new UsuarioDAO();
                receber = b.procuraUser("%" + jTextField1.getText() + "%");
                if (receber.size() == 0) {
                    DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
                    int n = tableModel.getRowCount();
                    for (int i = 0; i < n; i++) {
                        jTablePesquisa.setValueAt(null, i, 0);
                        jTablePesquisa.setValueAt(null, i, 1);
                        jTablePesquisa.setValueAt(null, i, 2);
                        jTablePesquisa.setValueAt(null, i, 3);
                    }
                    JOptionPane.showMessageDialog(null, "NAO ENCONTRADO");
                }
                for (int i = 0; i < receber.size(); ++i) {

                    DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
                    tableModel.setNumRows(receber.size());
                    jTablePesquisa.setValueAt(receber.get(i).getIdProprietario(), i, 0);
                    jTablePesquisa.setValueAt(receber.get(i).getNome(), i, 1);
                    jTablePesquisa.setValueAt(receber.get(i).getCpfcnpj(), i, 2);
                    jTablePesquisa.setValueAt(receber.get(i).getRg(), i, 3);
                }

            } catch (Exception ex) {
                Logger.getLogger(JDialogPProprietario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage() + "\n");
            }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
        DefaultTableModel tableModel = (DefaultTableModel) jTablePesquisa.getModel();
        int n = tableModel.getRowCount();
        for (int i = 0; i < n; i++) {
            jTablePesquisa.setValueAt(null, i, 0);
            jTablePesquisa.setValueAt(null, i, 1);
            jTablePesquisa.setValueAt(null, i, 2);
            jTablePesquisa.setValueAt(null, i, 3);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablePesquisaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTablePesquisaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePesquisaAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JDialogCadstAltera2 pp = new JDialogCadstAltera2(null, true);
        this.dispose();
        pp.setVisible(true);
        pp.setModal(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPProprietario dialog = new JDialogPProprietario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
