package Hibernate;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * Proprietarioimoveli generated by hbm2java
 */
public class Proprietarioimoveli  implements java.io.Serializable {


     private ProprietarioimoveliId id;
     private String demais;

    public Proprietarioimoveli() {
    }

    public Proprietarioimoveli(ProprietarioimoveliId id, String demais) {
       this.id = id;
       this.demais = demais;
    }
   
    public ProprietarioimoveliId getId() {
        return this.id;
    }
    
    public void setId(ProprietarioimoveliId id) {
        this.id = id;
    }
    public String getDemais() {
        return this.demais;
    }
    
    public void setDemais(String demais) {
        this.demais = demais;
    }




}


