package Hibernate;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * Proprietarioimovel2 generated by hbm2java
 */
public class Proprietarioimovel2  implements java.io.Serializable {


     private Proprietarioimovel2Id id;
     private String demais;

    public Proprietarioimovel2() {
    }

	
    public Proprietarioimovel2(Proprietarioimovel2Id id) {
        this.id = id;
    }
    public Proprietarioimovel2(Proprietarioimovel2Id id, String demais) {
       this.id = id;
       this.demais = demais;
    }
   
    public Proprietarioimovel2Id getId() {
        return this.id;
    }
    
    public void setId(Proprietarioimovel2Id id) {
        this.id = id;
    }
    public String getDemais() {
        return this.demais;
    }
    
    public void setDemais(String demais) {
        this.demais = demais;
    }




}


