package Hibernate;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * Imovelincra generated by hbm2java
 */
public class Imovelincra  implements java.io.Serializable {


     private String codIncra;
     private String nome;
     private String municipio;
     private String comarca;
     private String uf;
     private String matricula;
     private String Area;
     private String tipoProcesso;
     private String nomeArquivo;
     private String demais;

    public Imovelincra() {
    }

	
    public Imovelincra(String codIncra, String municipio, String comarca, String uf, String matricula, String Area, String tipoProcesso, String nomeArquivo) {
        this.codIncra = codIncra;
        this.municipio = municipio;
        this.comarca = comarca;
        this.uf = uf;
        this.matricula = matricula;
        this.Area = Area;
        this.tipoProcesso = tipoProcesso;
        this.nomeArquivo = nomeArquivo;
    }
    public Imovelincra(String codIncra, String nome, String municipio, String comarca, String uf, String matricula, String Area, String tipoProcesso, String nomeArquivo, String demais) {
       this.codIncra = codIncra;
       this.nome = nome;
       this.municipio = municipio;
       this.comarca = comarca;
       this.uf = uf;
       this.matricula = matricula;
       this.Area = Area;
       this.tipoProcesso = tipoProcesso;
       this.nomeArquivo = nomeArquivo;
       this.demais = demais;
    }
   
    public String getCodIncra() {
        return this.codIncra;
    }
    
    public void setCodIncra(String codIncra) {
        this.codIncra = codIncra;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getComarca() {
        return this.comarca;
    }
    
    public void setComarca(String comarca) {
        this.comarca = comarca;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getArea() {
        return this.Area;
    }
    
    public void setArea(String Area) {
        this.Area = Area;
    }
    public String getTipoProcesso() {
        return this.tipoProcesso;
    }
    
    public void setTipoProcesso(String tipoProcesso) {
        this.tipoProcesso = tipoProcesso;
    }
    public String getNomeArquivo() {
        return this.nomeArquivo;
    }
    
    public void setNomeArquivo(String nomeArquivo) {
        this.nomeArquivo = nomeArquivo;
    }
    public String getDemais() {
        return this.demais;
    }
    
    public void setDemais(String demais) {
        this.demais = demais;
    }




}


