package modelo;
// Generated 02/07/2013 03:06:14 by Hibernate Tools 3.6.0



/**
 * Proprietario generated by hbm2java
 */
public class Proprietario  implements java.io.Serializable {


     private Integer idProprietario;
     private String nome;
     private String cpfcnpj;
     private String rg;
     private String logradouro;
     private String end;
     private String nro;
     private String complemento;
     private String bairro;
     private String cidade;
     private String uf;
     private String cep;
     private String telefoneF;
     private String tefeloneC;
     private String email;
     private String senha;

    public Proprietario() {
    }

	
    public Proprietario(String nome, String cpfcnpj, String rg) {
        this.nome = nome;
        this.cpfcnpj = cpfcnpj;
        this.rg = rg;
    }
    public Proprietario(String nome, String cpfcnpj, String rg, String logradouro, String end, String nro, String complemento, String bairro, String cidade, String uf, String cep, String telefoneF, String tefeloneC, String email, String senha) {
       this.nome = nome;
       this.cpfcnpj = cpfcnpj;
       this.rg = rg;
       this.logradouro = logradouro;
       this.end = end;
       this.nro = nro;
       this.complemento = complemento;
       this.bairro = bairro;
       this.cidade = cidade;
       this.uf = uf;
       this.cep = cep;
       this.telefoneF = telefoneF;
       this.tefeloneC = tefeloneC;
       this.email = email;
       this.senha = senha;
    }
   
    public Integer getIdProprietario() {
        return this.idProprietario;
    }
    
    public void setIdProprietario(Integer idProprietario) {
        this.idProprietario = idProprietario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpfcnpj() {
        return this.cpfcnpj;
    }
    
    public void setCpfcnpj(String cpfcnpj) {
        this.cpfcnpj = cpfcnpj;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getTelefoneF() {
        return this.telefoneF;
    }
    
    public void setTelefoneF(String telefoneF) {
        this.telefoneF = telefoneF;
    }
    public String getTefeloneC() {
        return this.tefeloneC;
    }
    
    public void setTefeloneC(String tefeloneC) {
        this.tefeloneC = tefeloneC;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


